"""empty message

Revision ID: 01dbc5c8f865
Revises: 5bea85e27b8b
Create Date: 2023-02-02 00:21:01.003760

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '01dbc5c8f865'
down_revision = '5bea85e27b8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('show', schema=None) as batch_op:
        batch_op.add_column(sa.Column('venue_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('artist_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('time', sa.DateTime(), nullable=True))
        batch_op.drop_constraint('show_artist_fkey', type_='foreignkey')
        batch_op.drop_constraint('show_venue_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'venue', ['venue_id'], ['id'])
        batch_op.create_foreign_key(None, 'artist', ['artist_id'], ['id'])
        batch_op.drop_column('date')
        batch_op.drop_column('id')
        batch_op.drop_column('venue')
        batch_op.drop_column('artist')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('show', schema=None) as batch_op:
        batch_op.add_column(sa.Column('artist', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('venue', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
        batch_op.add_column(sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('show_venue_fkey', 'venue', ['venue'], ['id'])
        batch_op.create_foreign_key('show_artist_fkey', 'artist', ['artist'], ['id'])
        batch_op.drop_column('time')
        batch_op.drop_column('artist_id')
        batch_op.drop_column('venue_id')

    # ### end Alembic commands ###
